### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by JeffResc** [JeffResc/ShrekTimeConverter#1]
Create a README.md for the project and include it's live URL ([https://jeffresc.com/ShrekTimeConverter](https://jeffresc.com/ShrekTimeConverter)). The README.md file should include basic information about the project and a [short GIF](https://external-preview.redd.it/ti5zD26N21houaCuyZp-QBomWBoFbWg2g4jKNA8mXho.gif?s=51b2f968a50cc2de7229536f96b020a6ae4cee6c) (~15 seconds or less) demonstrating how the webpage looks along with some same input to show how the webpage reacts. This issue should be relatively easy for newcomers joining for Hacktoberfest. Please reply to this issue directly if you'd like to be assigned for this issue.

**Comment by 4RN4LDO** [comment]
I can work on this

**Comment by JeffResc** [comment]
@4RN4LDO, I've accepted #3, but if you have anything else to add, feel free to send a PR.
