### ISSUE TITLE
Remove the use of PHP

### ISSUE THREAD

**Issue by JeffResc** [JeffResc/ShrekTimeConverter#2]
PHP is used in this project to act as a hit counter for the site. I'd like to remove the use of PHP by utilizing a counter from [HitWebCounter.com](http://www.hitwebcounter.com/). This will replace the code on [lines 28-37](https://github.com/JeffResc/ShrekTimeConverter/blob/master/index.html#L28-L37). This should be a relatively easy issue to tackle for anyone who knows basic HTML skills. Please reply if you'd be interested in being assigned this issue for the project.

-----

Page Name for HitWebCounter.com: [https://jeffresc.com/ShrekTimeConverter](https://jeffresc.com/ShrekTimeConverter)

Starting Count: Current amount listed at the bottom of [https://jeffresc.com/ShrekTimeConverter](https://jeffresc.com/ShrekTimeConverter).

**Comment by yordanzhelevdev** [comment]
I can do this

**Comment by JeffResc** [comment]
Thanks, @yordanzhelevdev. Looks great. Accepted and merged.
